---

- hosts: all
  gather_facts: false
  tasks:

    - name: Install
      include_role:
        name: "{{ item }}"
      loop:
        - install-agent
        - add-host
      when: "zbx_deploy == True"

    - name: Uninstall
      include_role:
        name: "{{ item }}"
      loop:
#        - remove-host
        - uninstall-agent
      when: "zbx_deploy == False"

