---
# tasks file for remove-host

- name: Delete an existing host's info
  local_action:
    module: zabbix_host
    server_url: "http://{{ v_zbx_server }}/zabbix"
    login_user: "{{ v_zbx_username }}"
    login_password: "{{ v_zbx_password }}"
    host_name: "{{ inventory_hostname }}"
    state: absent
