---
# tasks file for add-host

- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - network
      - facter
  register: vminfo

- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: "http://{{ v_zbx_server }}/zabbix"
    login_user: "{{ v_zbx_username }}"
    login_password: "{{ v_zbx_password }}"
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    description:
    host_groups:
      - "{{ h_groups }}"
    status: enabled
    state: present
    interfaces:
      - type: 1
        main: 1
        useip: 0
        ip: "{{ vminfo.ansible_facts.ansible_ip_addresses[0] if vminfo.ansible_facts.ansible_os_family == 'Windows' else vminfo.ansible_facts.ansible_default_ipv4.address }}"
        dns: "{{ inventory_hostname }}"
        port: 10050

- name: Link Templates
  local_action:
    module: zabbix_host
    server_url: "http://{{ v_zbx_server }}/zabbix"
    login_user: "{{ v_zbx_username }}"
    login_password: "{{ v_zbx_password }}"
    host_name: "{{ inventory_hostname }}"
    link_templates:
       - "{{ item }}"
    force: no
  with_items:
    - "{{ l_template }}"
  register: host_config
