---

- name: Include vars of linux.yml
  include_vars:
    file: linux.yml

- name: (Linux) Stop Zabbix Agent service
  systemd:
    state: stopped
    name: zabbix-agent

- name: (Linux) Delete Service file
  file:
    path: "/usr/lib/systemd/system/zabbix-agent.service"
    state: absent

- name: (Linux) Remove Zabbix Agent Files
  file:
    path: "{{ v_zbx_lnx_install_path }}"
    state: absent

- name: (Linux) Remove the user 'zabbix'
  user:
    name: zabbix
    state: absent
    remove: yes
