---
- name: Include vars of windows.yml
  include_vars:
    file: windows.yml

- name: (Windows) Stop Zabbix Agent Service
  win_shell: "{{ v_zbx_install_path }}\\bin\\zabbix_agentd.exe -x"
  ignore_errors: yes

- name: (Windows) Uninstall Zabbix Agent Service
  win_shell: "{{ v_zbx_install_path }}\\bin\\zabbix_agentd.exe -d"
  ignore_errors: yes

- name: (Windows) Remove Zabbix Agent Directory
  win_file:
    path: "{{ v_zbx_install_path }}"
    state: absent
  ignore_errors: yes
