---
# tasks file for install-agent

- name: collect facts about system services
  service_facts:
  register: services_state

- name: Debug
  debug:
    var: services_state.ansible_facts.services['firewalld.service'].status
