- hosts: windows
  tasks:

  - name: Create Temporary Directory to Download Zabbix Agent Package
    win_tempfile:
      state: directory
      suffix: zabbix-agent
    register: temp
  
  - name: Download Zabbix Agent Package and checksum
    win_get_url:
      url: "{{ v_zbx_agent_url }}"
      dest: "{{ item }}\\zabbix_agent.zip"
      checksum: "{{ v_zbx_url_checksum }}"
      checksum_algorithm: "{{ v_zbx_url_checksum_algorithm }}"
      force: True
    with_items:
      - "{{ temp.path }}"
  
  - name: Unzip Zabbix Agent Package
    win_unzip:
      src: "{{ item }}\\zabbix_agent.zip"
      dest: "{{ v_zbx_install_path }}"
    with_items:
      - "{{ temp.path }}"
  
  - name: Remove Temporary Directory
    win_file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ temp.path }}"
  
  - name: Create Config File from a Jinja2 template
    win_template:
      src: templates/zabbix_agentd.conf.j2
      dest: "{{ v_zbx_install_path }}\\conf\\zabbix_agentd.conf"
  
  - name: Install Zabbix Agent Service
    win_shell: "{{ v_zbx_install_path }}\\bin\\zabbix_agentd.exe -c C:\\zabbix_agent\\conf\\zabbix_agentd.conf -i"
  
  - name: Start Zabbix Agent Service
    win_shell: "{{ v_zbx_install_path }}\\bin\\zabbix_agentd.exe -s"
