- name: (WINDOWS) Include vars of linux.yml
  include_vars:
    file: windows.yml

- name: (WINDOWS) Create Temporary Directory to Download Zabbix Agent Package
  win_tempfile:
    state: directory
    suffix: zabbix-agent
  register: temp

- name: (WINDOWS) Download Zabbix Agent Package and checksum
  win_get_url:
    url: "{{ v_zbx_agent_url }}"
    dest: "{{ temp.path }}\\zabbix_agent.zip"
    force: True

- name: (WINDOWS) Unzip Zabbix Agent Package
  win_unzip:
    src: "{{ temp.path }}\\zabbix_agent.zip"
    dest: "{{ v_zbx_install_path }}"

- name: (WINDOWS) Remove Temporary Directory
  win_file:
    path: "{{ temp.path }}"
    state: absent

- name: (WINDOWS) Create Config File from a Jinja2 template
  win_template:
    src: templates/windows_zabbix_agentd.conf.j2
    dest: "{{ v_zbx_install_path }}\\conf\\zabbix_agentd.conf"

- name: (WINDOWS) Install Zabbix Agent Service
  win_shell: "{{ v_zbx_install_path }}\\bin\\zabbix_agentd.exe -c {{ v_zbx_install_path }}\\conf\\zabbix_agentd.conf -i"

- name: (WINDOWS) Start Zabbix Agent Service
  win_shell: "{{ v_zbx_install_path }}\\bin\\zabbix_agentd.exe -s"
